import turtle
tao = turtle.Pen()
tao.shape('turtle')
tao.speed(10)
tao.rt(90)
for number in range(2):
    tao.begin_fill()
    tao.color('Black','LIme')
    tao.fd(100)
    tao.circle(26,210)
    tao.goto(0,0)
    tao.end_fill()
for number in range(2):
    tao.begin_fill()
    tao.color('Black','Blue')
    tao.fd(100)
    tao.circle(26,210)
    tao.goto(0,0)
    tao.end_fill()
for number in range(2):
    tao.color('Black','Red')
    tao.begin_fill()
    tao.fd(100)
    tao.circle(26,210)
    tao.goto(0,0)
    tao.end_fill()
for number in range(2):
    tao.color('Black','Purple')
    tao.begin_fill()
    tao.fd(100)
    tao.circle(26,210)
    tao.goto(0,0)
    tao.end_fill()
for number in range(2):
    tao.color('Black','Orange')
    tao.begin_fill()
    tao.fd(100)
    tao.circle(26,210)
    tao.goto(0,0)
    tao.end_fill()
for number in range(2):
    tao.color('Black','CYAN')
    tao.begin_fill()
    tao.fd(100)
    tao.circle(26,210)
    tao.goto(0,0)
    tao.end_fill()
tao.setpos(0,-50)
tao.lt(90)
tao.color('Black','Yellow')
tao.begin_fill()
tao.circle(50,360)
tao.end_fill()
tao.penup()
tao.setpos(-20,10)
tao.dot('black')
tao.setpos(20,10)
tao.dot('black')
tao.setpos(-35,-5)
tao.pendown()
tao.color('Black','white')
tao.begin_fill()
tao.fd(70)
tao.rt(90)
tao.circle(-35,180)
tao.end_fill()
tao.penup()
tao.setpos(0,25)
turtle.done()

